// Generated by CoffeeScript 1.6.3
(function() {
  var Repo, cleanUp, githubResults, info, repos, result, _i, _len;

  console.log('Initializing Qucik GitHub Info');

  githubResults = [];

  repos = [];

  cleanUp = function(input) {
    input = input.replace(/<em>/, "");
    input = input.replace(/<\/em>/, "");
    return input.split(" ")[0];
  };

  Repo = (function() {
    function Repo() {}

    Repo.prototype.initialize = function(repo) {
      return console.log(repo);
    };

    return Repo;

  })();

  $(".g").each(function() {
    var title;
    title = $(this).find("a:first").html();
    if (title.indexOf("GitHub") >= 0) {
      return githubResults.push(cleanUp(title));
    }
  });

  for (_i = 0, _len = githubResults.length; _i < _len; _i++) {
    result = githubResults[_i];
    info = result.split("/");
    repos.push({
      author: info[0],
      repoName: info[1]
    });
  }

}).call(this);
